/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoututilsImport } from './routes/_layoututils'
import { Route as LayoutImport } from './routes/_layout'
import { Route as AdminlayoutImport } from './routes/_adminlayout'
import { Route as LayoututilsSearchorderImport } from './routes/_layoututils/searchorder'
import { Route as LayoututilsRegisterImport } from './routes/_layoututils/register'
import { Route as LayoututilsCartlayoutImport } from './routes/_layoututils/_cartlayout'
import { Route as LayoutUserorderImport } from './routes/_layout/userorder'
import { Route as LayoutProfileImport } from './routes/_layout/profile'
import { Route as LayoutProductImport } from './routes/_layout/product'
import { Route as LayoutLoginImport } from './routes/_layout/login'
import { Route as AdminlayoutShopImport } from './routes/_adminlayout/shop'
import { Route as AdminlayoutSearchuserImport } from './routes/_adminlayout/searchuser'
import { Route as AdminlayoutManageuserImport } from './routes/_adminlayout/manageuser'
import { Route as AdminlayoutCategoryImport } from './routes/_adminlayout/category'
import { Route as AdminlayoutAdminorderImport } from './routes/_adminlayout/adminorder'
import { Route as AdminlayoutAdminImport } from './routes/_adminlayout/admin'
import { Route as AdminlayoutAddproductImport } from './routes/_adminlayout/addproduct'
import { Route as AdminlayoutAddmanagerImport } from './routes/_adminlayout/addmanager'
import { Route as AdminlayoutAddcodeImport } from './routes/_adminlayout/addcode'
import { Route as LayoututilsCartlayoutCartorderImport } from './routes/_layoututils/_cartlayout/cartorder'
import { Route as LayoututilsCartlayoutCartImport } from './routes/_layoututils/_cartlayout/cart'
import { Route as LayoutProductdetailProductIdImport } from './routes/_layout/productdetail/$productId'
import { Route as AdminlayoutAdminorderdetailOrderIdImport } from './routes/_adminlayout/adminorderdetail/$orderId'
import { Route as AdminlayoutAdminmanageproductPageproductImport } from './routes/_adminlayout/adminmanageproduct/$pageproduct'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const LayoututilsRoute = LayoututilsImport.update({
  id: '/_layoututils',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const AdminlayoutRoute = AdminlayoutImport.update({
  id: '/_adminlayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const LayoututilsSearchorderRoute = LayoututilsSearchorderImport.update({
  path: '/searchorder',
  getParentRoute: () => LayoututilsRoute,
} as any)

const LayoututilsRegisterRoute = LayoututilsRegisterImport.update({
  path: '/register',
  getParentRoute: () => LayoututilsRoute,
} as any)

const LayoututilsCartlayoutRoute = LayoututilsCartlayoutImport.update({
  id: '/_cartlayout',
  getParentRoute: () => LayoututilsRoute,
} as any)

const LayoutUserorderRoute = LayoutUserorderImport.update({
  path: '/userorder',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProfileRoute = LayoutProfileImport.update({
  path: '/profile',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProductRoute = LayoutProductImport.update({
  path: '/product',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutLoginRoute = LayoutLoginImport.update({
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)

const AdminlayoutShopRoute = AdminlayoutShopImport.update({
  path: '/shop',
  getParentRoute: () => AdminlayoutRoute,
} as any)

const AdminlayoutSearchuserRoute = AdminlayoutSearchuserImport.update({
  path: '/searchuser',
  getParentRoute: () => AdminlayoutRoute,
} as any)

const AdminlayoutManageuserRoute = AdminlayoutManageuserImport.update({
  path: '/manageuser',
  getParentRoute: () => AdminlayoutRoute,
} as any)

const AdminlayoutCategoryRoute = AdminlayoutCategoryImport.update({
  path: '/category',
  getParentRoute: () => AdminlayoutRoute,
} as any)

const AdminlayoutAdminorderRoute = AdminlayoutAdminorderImport.update({
  path: '/adminorder',
  getParentRoute: () => AdminlayoutRoute,
} as any)

const AdminlayoutAdminRoute = AdminlayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => AdminlayoutRoute,
} as any)

const AdminlayoutAddproductRoute = AdminlayoutAddproductImport.update({
  path: '/addproduct',
  getParentRoute: () => AdminlayoutRoute,
} as any)

const AdminlayoutAddmanagerRoute = AdminlayoutAddmanagerImport.update({
  path: '/addmanager',
  getParentRoute: () => AdminlayoutRoute,
} as any)

const AdminlayoutAddcodeRoute = AdminlayoutAddcodeImport.update({
  path: '/addcode',
  getParentRoute: () => AdminlayoutRoute,
} as any)

const LayoututilsCartlayoutCartorderRoute =
  LayoututilsCartlayoutCartorderImport.update({
    path: '/cartorder',
    getParentRoute: () => LayoututilsCartlayoutRoute,
  } as any)

const LayoututilsCartlayoutCartRoute = LayoututilsCartlayoutCartImport.update({
  path: '/cart',
  getParentRoute: () => LayoututilsCartlayoutRoute,
} as any)

const LayoutProductdetailProductIdRoute =
  LayoutProductdetailProductIdImport.update({
    path: '/productdetail/$productId',
    getParentRoute: () => LayoutRoute,
  } as any)

const AdminlayoutAdminorderdetailOrderIdRoute =
  AdminlayoutAdminorderdetailOrderIdImport.update({
    path: '/adminorderdetail/$orderId',
    getParentRoute: () => AdminlayoutRoute,
  } as any)

const AdminlayoutAdminmanageproductPageproductRoute =
  AdminlayoutAdminmanageproductPageproductImport.update({
    path: '/adminmanageproduct/$pageproduct',
    getParentRoute: () => AdminlayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_adminlayout': {
      id: '/_adminlayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminlayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layoututils': {
      id: '/_layoututils'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoututilsImport
      parentRoute: typeof rootRoute
    }
    '/_adminlayout/addcode': {
      id: '/_adminlayout/addcode'
      path: '/addcode'
      fullPath: '/addcode'
      preLoaderRoute: typeof AdminlayoutAddcodeImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_adminlayout/addmanager': {
      id: '/_adminlayout/addmanager'
      path: '/addmanager'
      fullPath: '/addmanager'
      preLoaderRoute: typeof AdminlayoutAddmanagerImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_adminlayout/addproduct': {
      id: '/_adminlayout/addproduct'
      path: '/addproduct'
      fullPath: '/addproduct'
      preLoaderRoute: typeof AdminlayoutAddproductImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_adminlayout/admin': {
      id: '/_adminlayout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminlayoutAdminImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_adminlayout/adminorder': {
      id: '/_adminlayout/adminorder'
      path: '/adminorder'
      fullPath: '/adminorder'
      preLoaderRoute: typeof AdminlayoutAdminorderImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_adminlayout/category': {
      id: '/_adminlayout/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof AdminlayoutCategoryImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_adminlayout/manageuser': {
      id: '/_adminlayout/manageuser'
      path: '/manageuser'
      fullPath: '/manageuser'
      preLoaderRoute: typeof AdminlayoutManageuserImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_adminlayout/searchuser': {
      id: '/_adminlayout/searchuser'
      path: '/searchuser'
      fullPath: '/searchuser'
      preLoaderRoute: typeof AdminlayoutSearchuserImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_adminlayout/shop': {
      id: '/_adminlayout/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof AdminlayoutShopImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/product': {
      id: '/_layout/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof LayoutProductImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/profile': {
      id: '/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProfileImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/userorder': {
      id: '/_layout/userorder'
      path: '/userorder'
      fullPath: '/userorder'
      preLoaderRoute: typeof LayoutUserorderImport
      parentRoute: typeof LayoutImport
    }
    '/_layoututils/_cartlayout': {
      id: '/_layoututils/_cartlayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoututilsCartlayoutImport
      parentRoute: typeof LayoututilsImport
    }
    '/_layoututils/register': {
      id: '/_layoututils/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof LayoututilsRegisterImport
      parentRoute: typeof LayoututilsImport
    }
    '/_layoututils/searchorder': {
      id: '/_layoututils/searchorder'
      path: '/searchorder'
      fullPath: '/searchorder'
      preLoaderRoute: typeof LayoututilsSearchorderImport
      parentRoute: typeof LayoututilsImport
    }
    '/_adminlayout/adminmanageproduct/$pageproduct': {
      id: '/_adminlayout/adminmanageproduct/$pageproduct'
      path: '/adminmanageproduct/$pageproduct'
      fullPath: '/adminmanageproduct/$pageproduct'
      preLoaderRoute: typeof AdminlayoutAdminmanageproductPageproductImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_adminlayout/adminorderdetail/$orderId': {
      id: '/_adminlayout/adminorderdetail/$orderId'
      path: '/adminorderdetail/$orderId'
      fullPath: '/adminorderdetail/$orderId'
      preLoaderRoute: typeof AdminlayoutAdminorderdetailOrderIdImport
      parentRoute: typeof AdminlayoutImport
    }
    '/_layout/productdetail/$productId': {
      id: '/_layout/productdetail/$productId'
      path: '/productdetail/$productId'
      fullPath: '/productdetail/$productId'
      preLoaderRoute: typeof LayoutProductdetailProductIdImport
      parentRoute: typeof LayoutImport
    }
    '/_layoututils/_cartlayout/cart': {
      id: '/_layoututils/_cartlayout/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof LayoututilsCartlayoutCartImport
      parentRoute: typeof LayoututilsCartlayoutImport
    }
    '/_layoututils/_cartlayout/cartorder': {
      id: '/_layoututils/_cartlayout/cartorder'
      path: '/cartorder'
      fullPath: '/cartorder'
      preLoaderRoute: typeof LayoututilsCartlayoutCartorderImport
      parentRoute: typeof LayoututilsCartlayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AdminlayoutRoute: AdminlayoutRoute.addChildren({
    AdminlayoutAddcodeRoute,
    AdminlayoutAddmanagerRoute,
    AdminlayoutAddproductRoute,
    AdminlayoutAdminRoute,
    AdminlayoutAdminorderRoute,
    AdminlayoutCategoryRoute,
    AdminlayoutManageuserRoute,
    AdminlayoutSearchuserRoute,
    AdminlayoutShopRoute,
    AdminlayoutAdminmanageproductPageproductRoute,
    AdminlayoutAdminorderdetailOrderIdRoute,
  }),
  LayoutRoute: LayoutRoute.addChildren({
    LayoutLoginRoute,
    LayoutProductRoute,
    LayoutProfileRoute,
    LayoutUserorderRoute,
    LayoutProductdetailProductIdRoute,
  }),
  LayoututilsRoute: LayoututilsRoute.addChildren({
    LayoututilsCartlayoutRoute: LayoututilsCartlayoutRoute.addChildren({
      LayoututilsCartlayoutCartRoute,
      LayoututilsCartlayoutCartorderRoute,
    }),
    LayoututilsRegisterRoute,
    LayoututilsSearchorderRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_adminlayout",
        "/_layout",
        "/_layoututils"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_adminlayout": {
      "filePath": "_adminlayout.tsx",
      "children": [
        "/_adminlayout/addcode",
        "/_adminlayout/addmanager",
        "/_adminlayout/addproduct",
        "/_adminlayout/admin",
        "/_adminlayout/adminorder",
        "/_adminlayout/category",
        "/_adminlayout/manageuser",
        "/_adminlayout/searchuser",
        "/_adminlayout/shop",
        "/_adminlayout/adminmanageproduct/$pageproduct",
        "/_adminlayout/adminorderdetail/$orderId"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/login",
        "/_layout/product",
        "/_layout/profile",
        "/_layout/userorder",
        "/_layout/productdetail/$productId"
      ]
    },
    "/_layoututils": {
      "filePath": "_layoututils.tsx",
      "children": [
        "/_layoututils/_cartlayout",
        "/_layoututils/register",
        "/_layoututils/searchorder"
      ]
    },
    "/_adminlayout/addcode": {
      "filePath": "_adminlayout/addcode.tsx",
      "parent": "/_adminlayout"
    },
    "/_adminlayout/addmanager": {
      "filePath": "_adminlayout/addmanager.tsx",
      "parent": "/_adminlayout"
    },
    "/_adminlayout/addproduct": {
      "filePath": "_adminlayout/addproduct.tsx",
      "parent": "/_adminlayout"
    },
    "/_adminlayout/admin": {
      "filePath": "_adminlayout/admin.tsx",
      "parent": "/_adminlayout"
    },
    "/_adminlayout/adminorder": {
      "filePath": "_adminlayout/adminorder.tsx",
      "parent": "/_adminlayout"
    },
    "/_adminlayout/category": {
      "filePath": "_adminlayout/category.tsx",
      "parent": "/_adminlayout"
    },
    "/_adminlayout/manageuser": {
      "filePath": "_adminlayout/manageuser.tsx",
      "parent": "/_adminlayout"
    },
    "/_adminlayout/searchuser": {
      "filePath": "_adminlayout/searchuser.tsx",
      "parent": "/_adminlayout"
    },
    "/_adminlayout/shop": {
      "filePath": "_adminlayout/shop.tsx",
      "parent": "/_adminlayout"
    },
    "/_layout/login": {
      "filePath": "_layout/login.tsx",
      "parent": "/_layout"
    },
    "/_layout/product": {
      "filePath": "_layout/product.tsx",
      "parent": "/_layout"
    },
    "/_layout/profile": {
      "filePath": "_layout/profile.tsx",
      "parent": "/_layout"
    },
    "/_layout/userorder": {
      "filePath": "_layout/userorder.tsx",
      "parent": "/_layout"
    },
    "/_layoututils/_cartlayout": {
      "filePath": "_layoututils/_cartlayout.tsx",
      "parent": "/_layoututils",
      "children": [
        "/_layoututils/_cartlayout/cart",
        "/_layoututils/_cartlayout/cartorder"
      ]
    },
    "/_layoututils/register": {
      "filePath": "_layoututils/register.tsx",
      "parent": "/_layoututils"
    },
    "/_layoututils/searchorder": {
      "filePath": "_layoututils/searchorder.tsx",
      "parent": "/_layoututils"
    },
    "/_adminlayout/adminmanageproduct/$pageproduct": {
      "filePath": "_adminlayout/adminmanageproduct/$pageproduct.tsx",
      "parent": "/_adminlayout"
    },
    "/_adminlayout/adminorderdetail/$orderId": {
      "filePath": "_adminlayout/adminorderdetail/$orderId.tsx",
      "parent": "/_adminlayout"
    },
    "/_layout/productdetail/$productId": {
      "filePath": "_layout/productdetail/$productId.tsx",
      "parent": "/_layout"
    },
    "/_layoututils/_cartlayout/cart": {
      "filePath": "_layoututils/_cartlayout/cart.tsx",
      "parent": "/_layoututils/_cartlayout"
    },
    "/_layoututils/_cartlayout/cartorder": {
      "filePath": "_layoututils/_cartlayout/cartorder.tsx",
      "parent": "/_layoututils/_cartlayout"
    }
  }
}
ROUTE_MANIFEST_END */
