#spring.application.name=shop-backend

spring:
  datasource:
    url: jdbc:mysql://localhost/clothes
    username: root
    password: 200124
    hikari:
      maximum-pool-size: 10
      minimum-idle: 4
      connection-timeout: 20000
      idle-timeout: 60000
      pool-name: HikariConnPool
      max-lifetime: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB


